services:
  - type: web
    name: diabetes-fast-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11

  - type: web
    name: diabetes-streamlit-ui
    runtime: python
    plan: free
    rootDir: frontend
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: BACKEND_URL
        value: https://diabetes-fast-api-8.onrender.com
